### PR TITLE
Feature Request: Allow for Indexing

### PR DESCRIPTION
**Pull request by maxdemarzi**
Allowing users to specify csv files for fulltext and exact indexing of nodes and relationships.

### CODE REVIEW

**Comment by jexp** [comment]
max could you squash your commits into one? with git rebase -i ccd110e "p"ick the first one and "s"quash the others into a single commit.

**Comment by maxdemarzi** [comment]
Done.

**Comment by jexp** [comment]
Thanks,

What do you think about my suggestion of skipping these additional index files and rather using the header for this? Seems less involved?

**Comment by maxdemarzi** [comment]
I think doing it this way we capture the more general case and avoid problems with:
- wanting a field to be indexed in two indexes
- indexes that use values not included in the nodes (I could see this for aliases, or i18n)
- easier to update the importer as you add a file without messing with your nodes.csv

**Comment by jexp** [comment]
I think those are rather the 10% use cases so I'm still not convinced that they are worth the effort :) 

I think I'll implement the other solution for the 90% case

**Comment by karussell** [comment]
Two side notes: always close writers/streams + do it in a finally clause and specify the encoding for the streams

**Comment by maxdemarzi** [comment]
I'm a Ruby guy, so I did what I could...    >8-]

Sounds like somebody (cough Peter cough) is volunteering a pull-request?

**Pull request merged**
