### PR TITLE
20

### PR DESCRIPTION
**Pull request by cescalante-carecloud**
Hi, 
Importing the original data in the nodes.csv and rels.csv files wasn't working for me. I gave the data in the branch 20 read-me file a shot (see below), didn't work either. What did end up working was using comma as opposed to tab delimiters. 

Not quite sure why the data in the readme didn't work, everything seemed to match the instructions elsewhere in the project. Maybe it's an issue with my text editor?
### nodes.csv from readme

```
name    l:label       age works_on
Michael Person,Father 37  neo4j
Selina  Person,Child  14
Rana    Person,Child  6
Selma   Person,Child  4
```
### sample/nodes.csv that worked for me

```
name,l:label,l:label,age,works_on
Michael,Person,Father,37,neo4j
Selina,Person,Child,14,
Rana,Person,Child,6,
Selma,Person,Child,4,
```
### rels.csv from readme

```
start   end type        since   counter:int
1     2   FATHER_OF 1998-07-10  1
1     3   FATHER_OF 2007-09-15  2
1     4   FATHER_OF 2008-05-03  3
3     4   SISTER_OF 2008-05-03  5
2     3   SISTER_OF 2007-09-15  7 
```
### sample/rels.csv that worked for me

```
start,end,type,since,counter:int
1,2,FATHER_OF,7/10/98,1
1,3,FATHER_OF,9/15/07,2
1,4,FATHER_OF,5/3/08,3
3,4,SISTER_OF,5/3/08,5
2,3,SISTER_OF,9/15/07,7
```

### CODE REVIEW

**Comment by cescalante-carecloud** [comment]
aww, the original version seems to be working normally now

**Comment by cescalante-carecloud** [comment]
nope, the master branch was working but branch 20 is the same

**Comment by jexp** [comment]
Data in the readme is space separated as markdown doesn't support something else.

**Comment by cescalante-carecloud** [comment]
Alright, TIL
Just to be clear, in branch 20, do I have to explicitly set batch_import.<something>.delim=<something> for all delimiters, including tab? 

I'm thinking that the reason tab-separated data didn't work for me is because I didn't explicitly set the delimiter. 

thanks

**Comment by jexp** [comment]
not that I know of, at least nothing in the code changed there. It still defaults to tab.

**Pull request closed without merging**
